name: primeiro_projeto_dart
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/APONTES19/Dart.git

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
